[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/profile"
  to = "/.netlify/functions/profile"
  status = 200

[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200

[[redirects]]
  from = "/api/admin-login"
  to = "/.netlify/functions/admin-login"
  status = 200

[[redirects]]
  from = "/api/admin-save"
  to = "/.netlify/functions/admin-save"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
